### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by dialvarezs** [mgalloy/cpu-vs-gpu#6]
Hey, I have some suggestions:
- Using the top-line Xeon instead of the i7, because it's more fair. If we don't care about a higher count of cores in the GPU, why limiting the CPU to 4/8 cores? It's chip vs chip, even nvidia apparently uses Xeon chips for their [plot](http://docs.nvidia.com/cuda/cuda-c-programming-guide/graphics/floating-point-operations-per-second.png).
- Using only base frequency in both CPU and GPU, because the turbo feature is unpredictable in some circumstances.
- Using only single-chip GPUs (byebye K80).

What do you think? If you agree with these points (or some of them) I can make a pull request making the changes.

**Comment by mgalloy** [comment]
Yes, I think all these changes would be good.

* I think the i7 values were in there because they were available at the time and it was never updated later when Xeon became available.
* I had already removed boost from the IDL generated plots, it should be easy to take them out of the Python generated plots.
* I was not aware that the K80 had multiple boards.

A pull request would be very appreciated!
